name: meu_card_flutter
description: "Regular card portfolio."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/me2.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Caveat
      fonts:
        - asset: fonts/Caveat-regular.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-regular.ttf

#    - family: Source Sans Pro
#      fonts:
#        - asset: fonts/SourceSansPro-Regular.ttf